name: playx_network
description: playx_network is a Wrapper around Dio that can perform api request with better error handling and easily get the result of any api request.
version: 0.6.0
homepage: https://sourcya.io
repository: https://github.com/playx-flutter/playx_network
issue_tracker: https://github.com/playx-flutter/playx_network/issues

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

topics:
    - playx
    - dio
    - network
    - api

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  sentry_dio: ^9.8.0
  talker_dio_logger: ^5.0.2
  playx_core: ^0.7.4
  dio_smart_retry: ^7.0.1
  dio_web_adapter: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

